[build]
  command = "npm install --legacy-peer-deps"
  publish = "public"
  functions = "functions"

[build.environment]
  NODE_VERSION = "20"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"

[functions]
  [functions.node_bundle]
  external_node_modules = ["express", "serverless-http", "mongoose", "bcryptjs", "cloudinary", "cookie-parser", "cors", "dotenv", "jsonwebtoken", "multer", "nodemailer", "validator", "zod", "express-mongo-sanitize", "express-rate-limit", "express-validator", "helmet", "hpp", "multer-storage-cloudinary"]

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://mohamed-rafat-portfolio.netlify.app"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With, Accept, Origin"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, PATCH, OPTIONS"
    Access-Control-Allow-Credentials = "true"

[[redirects]]
  from = "/api/v1/*"
  to = "/.netlify/functions/api/api/v1/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
